GEOPY-923: Add content for all EM loop configurations
MiraGeoscience/geoh5py pull request #403
Opened 2023-08-31 21:00 UTC by domfournier

**GEOPY-923 - Update EM survey docs**

2023-09-01 23:02 UTC, jamiefb requested changes
a couple small things

2023-09-01 23:02 UTC, jamiefb commented on docs/content/geoh5_format/analyst/objects.rst
> +    - "Inline offset property" ``uuid`` OR  "Crossline offset value" ``double``:
this also shows up in a couple places

2023-09-05 15:45 UTC, domfournier commented on docs/content/geoh5_format/analyst/objects.rst
> +        Frequency channels at which data are recorder.
Done

2023-09-05 15:45 UTC, domfournier commented on docs/content/geoh5_format/analyst/objects.rst
> +    - "Inline offset property" ``uuid`` OR  "Crossline offset value" ``double``:
Done

2023-09-05 16:57 UTC, jamiefb approved these changes

2023-09-05 22:28 UTC, merged