GEOPY-1148: bug with grid.object.copy()
MiraGeoscience/geoh5py pull request #441
Opened 2023-10-24 18:07 UTC by MatthieuCMira

In grid_object

Bug when copying grid_object containing a property group. Since propertygroups are contained in the children.

=> catch property groups with continue

2023-10-24 18:12 UTC, MatthieuCMira commented
monitoring_directory_copy() now copy the property group.
However, unlike data, it's been copied on the workspace, which leads to duplicate the propertygroups

2023-10-24 18:33 UTC, MatthieuCMira commented
I introduce an option in grid_object copy() which is copy_property_group.
It's an option now in monitoring directoy_copy.
If call "False", the porperty groups are not copied

2023-10-25 12:20 UTC, domfournier requested changes
Try to focus on the issue. Adding an option to a core method like `copy` is a much larger endeavour.

2023-10-25 12:20 UTC, domfournier commented on geoh5py/objects/grid_object.py
> +        copy_property_groups: bool = True,
Let's not just modify this class. This would technically have to be pushed to the base class.

2023-10-25 12:20 UTC, domfournier commented on geoh5py/ui_json/utils.py
> +                copy_property_groups=copy_property_groups,
Changing here will break the copy for all other entities that don't have the copy_property_groups, or don't 
have property_groups. Let's not do that now and focus on fixing the grid2d instead.

2023-10-25 12:33 UTC, domfournier commented
It is likely that we need to also check the mechanics in grid2d. Since `property_groups` don't have `values`, it will likely crash here
![image](https://github.com/MiraGeoscience/geoh5py/assets/55204635/6b6c528b-44e4-4358-98f9-1781b0b3cda1)

2023-10-25 12:47 UTC, MatthieuCMira commented
> e need to also check the mechanics in grid2d. Since `property_groups` don't have `values`, it will likely crash her

there is no copy in grid2d, it's in grid object.

2023-10-25 12:57 UTC, MatthieuCMira commented
The problem is not about the copy. It's working.

The problem is about copying property_groups.
When I "monitored_directory_copy"
It duplicates the property_group in the workspace.

We just have to correct this

2023-10-25 13:49 UTC, domfournier commented
> > e need to also check the mechanics in grid2d. Since `property_groups` don't have `values`, it will likely crash her
> 
> there is no copy in grid2d, it's in grid object.

Correct, but the `copy_from_extent` will likely break as well. Good time to fix this bug since related to the copy method. We can augment the test you wrote to use the `copy_from_extent`

2023-10-25 20:02 UTC, domfournier approved these changes
Fantastic, thanks for this.

2023-10-25 20:31 UTC, MatthieuCMira commented
pre-commit mypy is annoying about typing with subclass/superclass.

2023-10-26 12:23 UTC, domfournier approved these changes
Go for testintg.

2023-10-30 13:03 UTC, merged