Geopy 1456
MiraGeoscience/geoh5py pull request #549
Opened 2024-05-02 13:24 UTC by MatthieuCMira

update for pillow 10.3

2024-05-02 16:52 UTC, domfournier approved these changes

2024-05-02 16:52 UTC, domfournier commented on tests/coordinate_system_test.py
> +    image.save(tmp_path / r"testtif.tif", exif=image.getexif())  # working with 10.1
```suggestion
    image.save(tmp_path / r"testtif.tif", exif=image.getexif())
```

2024-05-06 13:25 UTC, MatthieuCMira commented
Merging?

2024-06-04 18:35 UTC, domfournier commented
@sebhmg This one never made it somehow. Guess we can add it to the last minute updates.

2024-06-05 15:53 UTC, sebhmg commented on pyproject.toml
> +Pillow = "^10.3.0"
**thought:** specifying `^10.3.0` allows any `10.x` version, while `~10.3.0` is any `10.3.x`

In the past, updating to a minor version broke the behavior at runtime. I would tend to limit to `~10.3.0`
Alos relocking  a repo with `^10.3.0` spec might lock on `10.5`, while a repo which has not been relocked yet will still use `10.3.0`. that create more discrepancy between repos.

it is quite depends on packages though. Some have more conservative policy on changing minor version.

2024-06-05 15:56 UTC, sebhmg requested changes
see suggestion about using version spec with `~` instead of `^`

2024-06-05 17:10 UTC, domfournier approved these changes

2024-06-05 17:10 UTC, domfournier commented on pyproject.toml
> +Pillow = "^10.3.0"
```suggestion
Pillow = "~10.3.0"
```

2024-06-05 18:01 UTC, sebhmg approved these changes

2024-06-05 18:04 UTC, merged